# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(default=0, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_dt', models.DateField(auto_now=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Транзакции',
                'verbose_name': 'Транзакция',
            },
        ),
        migrations.CreateModel(
            name='TypeTransactModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='Значение')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Типы',
                'verbose_name': 'Тип',
            },
        ),
        migrations.AddField(
            model_name='transactsmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.TypeTransactModel', verbose_name='Тип'),
        ),
    ]
