# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_auto_20171114_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactsmodel',
            name='bank',
        ),
        migrations.AddField(
            model_name='transactsmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='tr/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='value',
            field=models.CharField(max_length=15, verbose_name='Тег'),
        ),
        migrations.DeleteModel(
            name='BankModel',
        ),
    ]
