# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0006_auto_20171114_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactsmodel',
            name='pic',
            field=models.ImageField(blank=True, default='nope.png', upload_to='tr/', verbose_name='Документ'),
        ),
    ]
