# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_auto_20171114_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactsmodel',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
